### ISSUE TITLE
Actividad 2: Verificación del Estado de Sitios Web

### ISSUE THREAD

**Issue by giannitibaldi** [giannitibaldi/Aplicaciones_TCP_IP#2]
Historia de usuario:
Como usuario, quiero tener un script de Bash que me permita verificar el estado de un sitio web individual o realizar una verificación en masa de varios sitios web.

Criterios de Aceptación
Puedo ejecutar el script de Bash con una URL específica y obtener el código de estado del sitio web.
Si no proporciono una URL específica, el script utilizará una URL por defecto.
Puedo ejecutar el script con la opción -f seguida de un archivo válido que contenga una lista de sitios web.
Cuando ejecuto el script con la opción -f y un archivo válido, el script muestra el código de estado de cada sitio web en la lista.
El script muestra "UP!" si el código de estado es 200, y "DOWN" si es diferente de 200.
Definición de Terminado
El script de Bash cumple con los siguientes criterios:

Puede verificar el estado de un sitio web específico.
Puede utilizar una URL por defecto si no se proporciona una específica.
Puede realizar una verificación en masa utilizando la opción -f seguida de un archivo válido que contenga una lista de sitios web.
Muestra el código de estado de cada sitio web en la lista.
Muestra "UP!" si el código de estado es 200, y "DOWN" si es diferente de 200.
Versionado en github en el repositorio original
Resultado esperado:
script en el repositorio original
Tareas
Las tareas involucradas en el desarrollo de esta historia de usuario podrían ser:

Crear un script de Bash.
Implementar la lógica para verificar el estado de un sitio web específico.
Implementar la lógica para utilizar una URL por defecto si no se proporciona una específica.
Implementar la lógica para leer un archivo válido que contiene una lista de sitios web.
Implementar la lógica para iterar sobre los sitios web en el archivo y mostrar el código de estado de cada uno.
Implementar la lógica para mostrar "UP!" si el código de estado es 200, y "DOWN" si es diferente de 200.
Probar el script con casos de prueba para asegurar su correcto funcionamiento.
Realizar pruebas adicionales y solucionar cualquier problema identificado.
Documentar el script y proporcionar instrucciones de uso.
Output posible
2024-03-10 08:30:00 - https://www.example1.com - 200 - UP!
2024-03-10 08:30:00 - https://www.example2.com - 404 - DOWN
2024-03-10 08:30:00 - https://www.example3.com - 200 - UP!

**Comment by LucaPollano2000** [comment]
TODO MAL

**Comment by giannitibaldi** [comment]
Te voy a matar

**Comment by LucaPollano2000** [comment]
No se puede asi
